### ISSUE TITLE
issue with docker compose and missing config data

### ISSUE THREAD

**Issue by holzfelix** [ccrisan/motioneye#1873]
Hi togehther, I use the following docker-compose file. 

```
---
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    hostname: "motioneye"
    restart: "always"
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
      - /media/CamData:/media/CamData
```

It worked fine an hour ago^^ ... then I restartet the PC because I moved it to the cellar ... and now I got this error:

>     INFO: hello! this is motionEye server 0.42
> 
> 
> CRITICAL: config directory "/data/etc" does not exist or is not writable

What could be the issue in this case?
