### ISSUE TITLE
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/.../merged: too many levels of symbolic links

### ISSUE THREAD

**Issue by caiotramon** [ccrisan/motioneye#1881]
SO: Ubuntu 20.04 LTS
Docker version 19.03.9, build 9d988398e7
docker-compose version 1.26.0, build d4451659

whenever I try to start the container using docker-compose up or docker run, I receive the following error:
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/af968ff052028ad12dc2af83c989e215496f897b071d4db2c25914bc59412fc7/merged: too many levels of symbolic links
Any ideas of what could be happening?

Docker run command:

```
docker run \
  -rm \
  -d \
  -p 8765:8765 \
  --hostname="motioneye" \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data/motioneye/config:/etc/motioneye \
  -v /data/motioneye/videos:/var/lib/motioneye \
  ccrisan/motioneye:master-amd64
```

docker-compose.yml:
```
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - /home/.../motioneye/etc_motioneye:/etc/motioneye
      - /home/.../motioneye/var_lib_motioneye:/var/lib/motioneye

```
